/*
 * generated by Xtext 2.25.0
 */
package br.unb.cic.obron.ide;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class OberonStandaloneSetup extends OberonStandaloneSetupGenerated {

	public static void doSetup() {
		new OberonStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
