/*
 * generated by Xtext 2.25.0
 */
package br.unb.cic.obron.ide.ui.tests;

import br.unb.cic.obron.ide.ui.internal.IdeActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class OberonUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return IdeActivator.getInstance().getInjector("br.unb.cic.obron.ide.Oberon");
	}

}
