/*
 * generated by Xtext 2.25.0
 */
package br.unb.cic.obron.ide.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class OberonUiModule extends AbstractOberonUiModule {

	public OberonUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
