/**
 * generated by Xtext 2.25.0
 */
package br.unb.cic.obron.ide.oberon;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declarations</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.unb.cic.obron.ide.oberon.OberonPackage#getDeclarations()
 * @model
 * @generated
 */
public interface Declarations extends EObject
{
} // Declarations
