/**
 * generated by Xtext 2.25.0
 */
package br.unb.cic.obron.ide.oberon;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Formal Arg</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.unb.cic.obron.ide.oberon.FormalArg#getArgs <em>Args</em>}</li>
 *   <li>{@link br.unb.cic.obron.ide.oberon.FormalArg#getArgType <em>Arg Type</em>}</li>
 * </ul>
 *
 * @see br.unb.cic.obron.ide.oberon.OberonPackage#getFormalArg()
 * @model
 * @generated
 */
public interface FormalArg extends EObject
{
  /**
   * Returns the value of the '<em><b>Args</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' attribute list.
   * @see br.unb.cic.obron.ide.oberon.OberonPackage#getFormalArg_Args()
   * @model unique="false"
   * @generated
   */
  EList<String> getArgs();

  /**
   * Returns the value of the '<em><b>Arg Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arg Type</em>' containment reference.
   * @see #setArgType(OberonType)
   * @see br.unb.cic.obron.ide.oberon.OberonPackage#getFormalArg_ArgType()
   * @model containment="true"
   * @generated
   */
  OberonType getArgType();

  /**
   * Sets the value of the '{@link br.unb.cic.obron.ide.oberon.FormalArg#getArgType <em>Arg Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arg Type</em>' containment reference.
   * @see #getArgType()
   * @generated
   */
  void setArgType(OberonType value);

} // FormalArg
