/**
 * generated by Xtext 2.25.0
 */
package br.unb.cic.obron.ide.oberon;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Formals</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.unb.cic.obron.ide.oberon.Formals#getArg <em>Arg</em>}</li>
 *   <li>{@link br.unb.cic.obron.ide.oberon.Formals#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see br.unb.cic.obron.ide.oberon.OberonPackage#getFormals()
 * @model
 * @generated
 */
public interface Formals extends EObject
{
  /**
   * Returns the value of the '<em><b>Arg</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arg</em>' containment reference.
   * @see #setArg(FormalArg)
   * @see br.unb.cic.obron.ide.oberon.OberonPackage#getFormals_Arg()
   * @model containment="true"
   * @generated
   */
  FormalArg getArg();

  /**
   * Sets the value of the '{@link br.unb.cic.obron.ide.oberon.Formals#getArg <em>Arg</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arg</em>' containment reference.
   * @see #getArg()
   * @generated
   */
  void setArg(FormalArg value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference list.
   * The list contents are of type {@link br.unb.cic.obron.ide.oberon.FormalArg}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference list.
   * @see br.unb.cic.obron.ide.oberon.OberonPackage#getFormals_Args()
   * @model containment="true"
   * @generated
   */
  EList<FormalArg> getArgs();

} // Formals
