/**
 * generated by Xtext 2.25.0
 */
package br.unb.cic.obron.ide.oberon;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Integer</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see br.unb.cic.obron.ide.oberon.OberonPackage#getInteger()
 * @model
 * @generated
 */
public interface Integer extends OberonType
{
} // Integer
