/**
 * generated by Xtext 2.25.0
 */
package br.unb.cic.obron.ide.oberon;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.unb.cic.obron.ide.oberon.OberonType#getName <em>Name</em>}</li>
 *   <li>{@link br.unb.cic.obron.ide.oberon.OberonType#getNumElement <em>Num Element</em>}</li>
 *   <li>{@link br.unb.cic.obron.ide.oberon.OberonType#getNameType <em>Name Type</em>}</li>
 * </ul>
 *
 * @see br.unb.cic.obron.ide.oberon.OberonPackage#getOberonType()
 * @model
 * @generated
 */
public interface OberonType extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see br.unb.cic.obron.ide.oberon.OberonPackage#getOberonType_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link br.unb.cic.obron.ide.oberon.OberonType#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Num Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Num Element</em>' attribute.
   * @see #setNumElement(int)
   * @see br.unb.cic.obron.ide.oberon.OberonPackage#getOberonType_NumElement()
   * @model
   * @generated
   */
  int getNumElement();

  /**
   * Sets the value of the '{@link br.unb.cic.obron.ide.oberon.OberonType#getNumElement <em>Num Element</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Num Element</em>' attribute.
   * @see #getNumElement()
   * @generated
   */
  void setNumElement(int value);

  /**
   * Returns the value of the '<em><b>Name Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name Type</em>' containment reference.
   * @see #setNameType(OberonType)
   * @see br.unb.cic.obron.ide.oberon.OberonPackage#getOberonType_NameType()
   * @model containment="true"
   * @generated
   */
  OberonType getNameType();

  /**
   * Sets the value of the '{@link br.unb.cic.obron.ide.oberon.OberonType#getNameType <em>Name Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name Type</em>' containment reference.
   * @see #getNameType()
   * @generated
   */
  void setNameType(OberonType value);

} // OberonType
