/**
 * generated by Xtext 2.25.0
 */
package br.unb.cic.obron.ide.oberon;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see br.unb.cic.obron.ide.oberon.OberonFactory
 * @model kind="package"
 * @generated
 */
public interface OberonPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "oberon";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.unb.br/cic/obron/ide/Oberon";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "oberon";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  OberonPackage eINSTANCE = br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl.init();

  /**
   * The meta object id for the '{@link br.unb.cic.obron.ide.oberon.impl.OberonImpl <em>Oberon</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.obron.ide.oberon.impl.OberonImpl
   * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getOberon()
   * @generated
   */
  int OBERON = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBERON__NAME = 0;

  /**
   * The feature id for the '<em><b>Declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBERON__DECLARATION = 1;

  /**
   * The feature id for the '<em><b>Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBERON__BLOCK = 2;

  /**
   * The number of structural features of the '<em>Oberon</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBERON_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link br.unb.cic.obron.ide.oberon.impl.BlockImpl <em>Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.obron.ide.oberon.impl.BlockImpl
   * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getBlock()
   * @generated
   */
  int BLOCK = 1;

  /**
   * The feature id for the '<em><b>Stmt</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK__STMT = 0;

  /**
   * The number of structural features of the '<em>Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link br.unb.cic.obron.ide.oberon.impl.DeclarationsImpl <em>Declarations</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.obron.ide.oberon.impl.DeclarationsImpl
   * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getDeclarations()
   * @generated
   */
  int DECLARATIONS = 2;

  /**
   * The number of structural features of the '<em>Declarations</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATIONS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link br.unb.cic.obron.ide.oberon.impl.UserTypeDeclarationImpl <em>User Type Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.obron.ide.oberon.impl.UserTypeDeclarationImpl
   * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getUserTypeDeclaration()
   * @generated
   */
  int USER_TYPE_DECLARATION = 3;

  /**
   * The feature id for the '<em><b>Name Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_TYPE_DECLARATION__NAME_TYPE = 0;

  /**
   * The feature id for the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_TYPE_DECLARATION__LENGTH = 1;

  /**
   * The feature id for the '<em><b>Vartype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_TYPE_DECLARATION__VARTYPE = 2;

  /**
   * The feature id for the '<em><b>Vars</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_TYPE_DECLARATION__VARS = 3;

  /**
   * The number of structural features of the '<em>User Type Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_TYPE_DECLARATION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link br.unb.cic.obron.ide.oberon.impl.ConstantImpl <em>Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.obron.ide.oberon.impl.ConstantImpl
   * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getConstant()
   * @generated
   */
  int CONSTANT = 4;

  /**
   * The feature id for the '<em><b>Const Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT__CONST_NAME = 0;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT__EXP = 1;

  /**
   * The number of structural features of the '<em>Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.unb.cic.obron.ide.oberon.impl.VarDeclarationImpl <em>Var Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.obron.ide.oberon.impl.VarDeclarationImpl
   * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getVarDeclaration()
   * @generated
   */
  int VAR_DECLARATION = 5;

  /**
   * The feature id for the '<em><b>Vars</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECLARATION__VARS = 0;

  /**
   * The feature id for the '<em><b>Var Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECLARATION__VAR_TYPE = 1;

  /**
   * The number of structural features of the '<em>Var Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_DECLARATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.unb.cic.obron.ide.oberon.impl.ProcedureImpl <em>Procedure</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.obron.ide.oberon.impl.ProcedureImpl
   * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getProcedure()
   * @generated
   */
  int PROCEDURE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCEDURE__NAME = 0;

  /**
   * The feature id for the '<em><b>Formals</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCEDURE__FORMALS = 1;

  /**
   * The feature id for the '<em><b>Procedure Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCEDURE__PROCEDURE_TYPE = 2;

  /**
   * The feature id for the '<em><b>Decl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCEDURE__DECL = 3;

  /**
   * The feature id for the '<em><b>Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCEDURE__BLOCK = 4;

  /**
   * The number of structural features of the '<em>Procedure</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROCEDURE_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link br.unb.cic.obron.ide.oberon.impl.FormalsImpl <em>Formals</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.obron.ide.oberon.impl.FormalsImpl
   * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getFormals()
   * @generated
   */
  int FORMALS = 7;

  /**
   * The feature id for the '<em><b>Arg</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMALS__ARG = 0;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMALS__ARGS = 1;

  /**
   * The number of structural features of the '<em>Formals</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMALS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.unb.cic.obron.ide.oberon.impl.FormalArgImpl <em>Formal Arg</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.obron.ide.oberon.impl.FormalArgImpl
   * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getFormalArg()
   * @generated
   */
  int FORMAL_ARG = 8;

  /**
   * The feature id for the '<em><b>Args</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMAL_ARG__ARGS = 0;

  /**
   * The feature id for the '<em><b>Arg Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMAL_ARG__ARG_TYPE = 1;

  /**
   * The number of structural features of the '<em>Formal Arg</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMAL_ARG_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.unb.cic.obron.ide.oberon.impl.ArgumentsImpl <em>Arguments</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.obron.ide.oberon.impl.ArgumentsImpl
   * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getArguments()
   * @generated
   */
  int ARGUMENTS = 9;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARGUMENTS__EXP = 0;

  /**
   * The feature id for the '<em><b>Exps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARGUMENTS__EXPS = 1;

  /**
   * The number of structural features of the '<em>Arguments</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARGUMENTS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.unb.cic.obron.ide.oberon.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.obron.ide.oberon.impl.ExpressionImpl
   * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 10;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__LEFT = 0;

  /**
   * The feature id for the '<em><b>Opr</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__OPR = 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__RIGHT = 2;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__EXP = 3;

  /**
   * The feature id for the '<em><b>Intvalue</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__INTVALUE = 4;

  /**
   * The feature id for the '<em><b>Boolvalue</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__BOOLVALUE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__NAME = 6;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__ARGS = 7;

  /**
   * The feature id for the '<em><b>Atribs</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__ATRIBS = 8;

  /**
   * The feature id for the '<em><b>Index</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__INDEX = 9;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 10;

  /**
   * The meta object id for the '{@link br.unb.cic.obron.ide.oberon.impl.OperationImpl <em>Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.obron.ide.oberon.impl.OperationImpl
   * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getOperation()
   * @generated
   */
  int OPERATION = 11;

  /**
   * The feature id for the '<em><b>Operation Relacional</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__OPERATION_RELACIONAL = 0;

  /**
   * The feature id for the '<em><b>Operation Aritmetic</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__OPERATION_ARITMETIC = 1;

  /**
   * The feature id for the '<em><b>Operation Logic</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION__OPERATION_LOGIC = 2;

  /**
   * The number of structural features of the '<em>Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link br.unb.cic.obron.ide.oberon.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.obron.ide.oberon.impl.StatementImpl
   * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 12;

  /**
   * The feature id for the '<em><b>Stmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__STMT = 0;

  /**
   * The feature id for the '<em><b>Stmts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__STMTS = 1;

  /**
   * The feature id for the '<em><b>Des</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__DES = 2;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__EXP = 3;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__VAR = 4;

  /**
   * The feature id for the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__COND = 5;

  /**
   * The feature id for the '<em><b>Then Stmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__THEN_STMT = 6;

  /**
   * The feature id for the '<em><b>Elsifs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__ELSIFS = 7;

  /**
   * The feature id for the '<em><b>Else Stmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__ELSE_STMT = 8;

  /**
   * The feature id for the '<em><b>Init</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__INIT = 9;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__CONDITION = 10;

  /**
   * The feature id for the '<em><b>Min</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__MIN = 11;

  /**
   * The feature id for the '<em><b>Max</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__MAX = 12;

  /**
   * The feature id for the '<em><b>Case</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__CASE = 13;

  /**
   * The feature id for the '<em><b>Cases</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__CASES = 14;

  /**
   * The feature id for the '<em><b>Exit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__EXIT = 15;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 16;

  /**
   * The meta object id for the '{@link br.unb.cic.obron.ide.oberon.impl.DesignatorImpl <em>Designator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.obron.ide.oberon.impl.DesignatorImpl
   * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getDesignator()
   * @generated
   */
  int DESIGNATOR = 13;

  /**
   * The feature id for the '<em><b>Designator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESIGNATOR__DESIGNATOR = 0;

  /**
   * The feature id for the '<em><b>Indexes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESIGNATOR__INDEXES = 1;

  /**
   * The feature id for the '<em><b>Atribs</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESIGNATOR__ATRIBS = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESIGNATOR__NAME = 3;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESIGNATOR__ARGS = 4;

  /**
   * The number of structural features of the '<em>Designator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESIGNATOR_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link br.unb.cic.obron.ide.oberon.impl.caseAlternativeImpl <em>case Alternative</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.obron.ide.oberon.impl.caseAlternativeImpl
   * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getcaseAlternative()
   * @generated
   */
  int CASE_ALTERNATIVE = 14;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CASE_ALTERNATIVE__EXP = 0;

  /**
   * The feature id for the '<em><b>Max</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CASE_ALTERNATIVE__MAX = 1;

  /**
   * The feature id for the '<em><b>Stmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CASE_ALTERNATIVE__STMT = 2;

  /**
   * The number of structural features of the '<em>case Alternative</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CASE_ALTERNATIVE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link br.unb.cic.obron.ide.oberon.impl.elseIfStmtImpl <em>else If Stmt</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.obron.ide.oberon.impl.elseIfStmtImpl
   * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getelseIfStmt()
   * @generated
   */
  int ELSE_IF_STMT = 15;

  /**
   * The feature id for the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELSE_IF_STMT__COND = 0;

  /**
   * The feature id for the '<em><b>Stmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELSE_IF_STMT__STMT = 1;

  /**
   * The number of structural features of the '<em>else If Stmt</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELSE_IF_STMT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link br.unb.cic.obron.ide.oberon.impl.OberonTypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.obron.ide.oberon.impl.OberonTypeImpl
   * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getOberonType()
   * @generated
   */
  int OBERON_TYPE = 16;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBERON_TYPE__NAME = 0;

  /**
   * The feature id for the '<em><b>Num Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBERON_TYPE__NUM_ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Name Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBERON_TYPE__NAME_TYPE = 2;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBERON_TYPE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link br.unb.cic.obron.ide.oberon.impl.DeclararionImpl <em>Declararion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.obron.ide.oberon.impl.DeclararionImpl
   * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getDeclararion()
   * @generated
   */
  int DECLARARION = 17;

  /**
   * The feature id for the '<em><b>Types</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARARION__TYPES = DECLARATIONS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Consts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARARION__CONSTS = DECLARATIONS_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Vars</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARARION__VARS = DECLARATIONS_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Proc</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARARION__PROC = DECLARATIONS_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Declararion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARARION_FEATURE_COUNT = DECLARATIONS_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link br.unb.cic.obron.ide.oberon.impl.IntegerImpl <em>Integer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.obron.ide.oberon.impl.IntegerImpl
   * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getInteger()
   * @generated
   */
  int INTEGER = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGER__NAME = OBERON_TYPE__NAME;

  /**
   * The feature id for the '<em><b>Num Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGER__NUM_ELEMENT = OBERON_TYPE__NUM_ELEMENT;

  /**
   * The feature id for the '<em><b>Name Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGER__NAME_TYPE = OBERON_TYPE__NAME_TYPE;

  /**
   * The number of structural features of the '<em>Integer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGER_FEATURE_COUNT = OBERON_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link br.unb.cic.obron.ide.oberon.impl.BooleanImpl <em>Boolean</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see br.unb.cic.obron.ide.oberon.impl.BooleanImpl
   * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getBoolean()
   * @generated
   */
  int BOOLEAN = 19;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN__NAME = OBERON_TYPE__NAME;

  /**
   * The feature id for the '<em><b>Num Element</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN__NUM_ELEMENT = OBERON_TYPE__NUM_ELEMENT;

  /**
   * The feature id for the '<em><b>Name Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN__NAME_TYPE = OBERON_TYPE__NAME_TYPE;

  /**
   * The number of structural features of the '<em>Boolean</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_FEATURE_COUNT = OBERON_TYPE_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link br.unb.cic.obron.ide.oberon.Oberon <em>Oberon</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Oberon</em>'.
   * @see br.unb.cic.obron.ide.oberon.Oberon
   * @generated
   */
  EClass getOberon();

  /**
   * Returns the meta object for the attribute '{@link br.unb.cic.obron.ide.oberon.Oberon#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see br.unb.cic.obron.ide.oberon.Oberon#getName()
   * @see #getOberon()
   * @generated
   */
  EAttribute getOberon_Name();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.Oberon#getDeclaration <em>Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Declaration</em>'.
   * @see br.unb.cic.obron.ide.oberon.Oberon#getDeclaration()
   * @see #getOberon()
   * @generated
   */
  EReference getOberon_Declaration();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.Oberon#getBlock <em>Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Block</em>'.
   * @see br.unb.cic.obron.ide.oberon.Oberon#getBlock()
   * @see #getOberon()
   * @generated
   */
  EReference getOberon_Block();

  /**
   * Returns the meta object for class '{@link br.unb.cic.obron.ide.oberon.Block <em>Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Block</em>'.
   * @see br.unb.cic.obron.ide.oberon.Block
   * @generated
   */
  EClass getBlock();

  /**
   * Returns the meta object for the containment reference list '{@link br.unb.cic.obron.ide.oberon.Block#getStmt <em>Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Stmt</em>'.
   * @see br.unb.cic.obron.ide.oberon.Block#getStmt()
   * @see #getBlock()
   * @generated
   */
  EReference getBlock_Stmt();

  /**
   * Returns the meta object for class '{@link br.unb.cic.obron.ide.oberon.Declarations <em>Declarations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declarations</em>'.
   * @see br.unb.cic.obron.ide.oberon.Declarations
   * @generated
   */
  EClass getDeclarations();

  /**
   * Returns the meta object for class '{@link br.unb.cic.obron.ide.oberon.UserTypeDeclaration <em>User Type Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>User Type Declaration</em>'.
   * @see br.unb.cic.obron.ide.oberon.UserTypeDeclaration
   * @generated
   */
  EClass getUserTypeDeclaration();

  /**
   * Returns the meta object for the attribute '{@link br.unb.cic.obron.ide.oberon.UserTypeDeclaration#getNameType <em>Name Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name Type</em>'.
   * @see br.unb.cic.obron.ide.oberon.UserTypeDeclaration#getNameType()
   * @see #getUserTypeDeclaration()
   * @generated
   */
  EAttribute getUserTypeDeclaration_NameType();

  /**
   * Returns the meta object for the attribute '{@link br.unb.cic.obron.ide.oberon.UserTypeDeclaration#getLength <em>Length</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Length</em>'.
   * @see br.unb.cic.obron.ide.oberon.UserTypeDeclaration#getLength()
   * @see #getUserTypeDeclaration()
   * @generated
   */
  EAttribute getUserTypeDeclaration_Length();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.UserTypeDeclaration#getVartype <em>Vartype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Vartype</em>'.
   * @see br.unb.cic.obron.ide.oberon.UserTypeDeclaration#getVartype()
   * @see #getUserTypeDeclaration()
   * @generated
   */
  EReference getUserTypeDeclaration_Vartype();

  /**
   * Returns the meta object for the containment reference list '{@link br.unb.cic.obron.ide.oberon.UserTypeDeclaration#getVars <em>Vars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Vars</em>'.
   * @see br.unb.cic.obron.ide.oberon.UserTypeDeclaration#getVars()
   * @see #getUserTypeDeclaration()
   * @generated
   */
  EReference getUserTypeDeclaration_Vars();

  /**
   * Returns the meta object for class '{@link br.unb.cic.obron.ide.oberon.Constant <em>Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constant</em>'.
   * @see br.unb.cic.obron.ide.oberon.Constant
   * @generated
   */
  EClass getConstant();

  /**
   * Returns the meta object for the attribute '{@link br.unb.cic.obron.ide.oberon.Constant#getConstName <em>Const Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Const Name</em>'.
   * @see br.unb.cic.obron.ide.oberon.Constant#getConstName()
   * @see #getConstant()
   * @generated
   */
  EAttribute getConstant_ConstName();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.Constant#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see br.unb.cic.obron.ide.oberon.Constant#getExp()
   * @see #getConstant()
   * @generated
   */
  EReference getConstant_Exp();

  /**
   * Returns the meta object for class '{@link br.unb.cic.obron.ide.oberon.VarDeclaration <em>Var Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var Declaration</em>'.
   * @see br.unb.cic.obron.ide.oberon.VarDeclaration
   * @generated
   */
  EClass getVarDeclaration();

  /**
   * Returns the meta object for the attribute list '{@link br.unb.cic.obron.ide.oberon.VarDeclaration#getVars <em>Vars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Vars</em>'.
   * @see br.unb.cic.obron.ide.oberon.VarDeclaration#getVars()
   * @see #getVarDeclaration()
   * @generated
   */
  EAttribute getVarDeclaration_Vars();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.VarDeclaration#getVarType <em>Var Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Var Type</em>'.
   * @see br.unb.cic.obron.ide.oberon.VarDeclaration#getVarType()
   * @see #getVarDeclaration()
   * @generated
   */
  EReference getVarDeclaration_VarType();

  /**
   * Returns the meta object for class '{@link br.unb.cic.obron.ide.oberon.Procedure <em>Procedure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Procedure</em>'.
   * @see br.unb.cic.obron.ide.oberon.Procedure
   * @generated
   */
  EClass getProcedure();

  /**
   * Returns the meta object for the attribute '{@link br.unb.cic.obron.ide.oberon.Procedure#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see br.unb.cic.obron.ide.oberon.Procedure#getName()
   * @see #getProcedure()
   * @generated
   */
  EAttribute getProcedure_Name();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.Procedure#getFormals <em>Formals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Formals</em>'.
   * @see br.unb.cic.obron.ide.oberon.Procedure#getFormals()
   * @see #getProcedure()
   * @generated
   */
  EReference getProcedure_Formals();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.Procedure#getProcedureType <em>Procedure Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Procedure Type</em>'.
   * @see br.unb.cic.obron.ide.oberon.Procedure#getProcedureType()
   * @see #getProcedure()
   * @generated
   */
  EReference getProcedure_ProcedureType();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.Procedure#getDecl <em>Decl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Decl</em>'.
   * @see br.unb.cic.obron.ide.oberon.Procedure#getDecl()
   * @see #getProcedure()
   * @generated
   */
  EReference getProcedure_Decl();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.Procedure#getBlock <em>Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Block</em>'.
   * @see br.unb.cic.obron.ide.oberon.Procedure#getBlock()
   * @see #getProcedure()
   * @generated
   */
  EReference getProcedure_Block();

  /**
   * Returns the meta object for class '{@link br.unb.cic.obron.ide.oberon.Formals <em>Formals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Formals</em>'.
   * @see br.unb.cic.obron.ide.oberon.Formals
   * @generated
   */
  EClass getFormals();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.Formals#getArg <em>Arg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Arg</em>'.
   * @see br.unb.cic.obron.ide.oberon.Formals#getArg()
   * @see #getFormals()
   * @generated
   */
  EReference getFormals_Arg();

  /**
   * Returns the meta object for the containment reference list '{@link br.unb.cic.obron.ide.oberon.Formals#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Args</em>'.
   * @see br.unb.cic.obron.ide.oberon.Formals#getArgs()
   * @see #getFormals()
   * @generated
   */
  EReference getFormals_Args();

  /**
   * Returns the meta object for class '{@link br.unb.cic.obron.ide.oberon.FormalArg <em>Formal Arg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Formal Arg</em>'.
   * @see br.unb.cic.obron.ide.oberon.FormalArg
   * @generated
   */
  EClass getFormalArg();

  /**
   * Returns the meta object for the attribute list '{@link br.unb.cic.obron.ide.oberon.FormalArg#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Args</em>'.
   * @see br.unb.cic.obron.ide.oberon.FormalArg#getArgs()
   * @see #getFormalArg()
   * @generated
   */
  EAttribute getFormalArg_Args();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.FormalArg#getArgType <em>Arg Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Arg Type</em>'.
   * @see br.unb.cic.obron.ide.oberon.FormalArg#getArgType()
   * @see #getFormalArg()
   * @generated
   */
  EReference getFormalArg_ArgType();

  /**
   * Returns the meta object for class '{@link br.unb.cic.obron.ide.oberon.Arguments <em>Arguments</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Arguments</em>'.
   * @see br.unb.cic.obron.ide.oberon.Arguments
   * @generated
   */
  EClass getArguments();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.Arguments#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see br.unb.cic.obron.ide.oberon.Arguments#getExp()
   * @see #getArguments()
   * @generated
   */
  EReference getArguments_Exp();

  /**
   * Returns the meta object for the containment reference list '{@link br.unb.cic.obron.ide.oberon.Arguments#getExps <em>Exps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Exps</em>'.
   * @see br.unb.cic.obron.ide.oberon.Arguments#getExps()
   * @see #getArguments()
   * @generated
   */
  EReference getArguments_Exps();

  /**
   * Returns the meta object for class '{@link br.unb.cic.obron.ide.oberon.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see br.unb.cic.obron.ide.oberon.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.Expression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see br.unb.cic.obron.ide.oberon.Expression#getLeft()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Left();

  /**
   * Returns the meta object for the containment reference list '{@link br.unb.cic.obron.ide.oberon.Expression#getOpr <em>Opr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Opr</em>'.
   * @see br.unb.cic.obron.ide.oberon.Expression#getOpr()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Opr();

  /**
   * Returns the meta object for the containment reference list '{@link br.unb.cic.obron.ide.oberon.Expression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right</em>'.
   * @see br.unb.cic.obron.ide.oberon.Expression#getRight()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Right();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.Expression#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see br.unb.cic.obron.ide.oberon.Expression#getExp()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Exp();

  /**
   * Returns the meta object for the attribute '{@link br.unb.cic.obron.ide.oberon.Expression#getIntvalue <em>Intvalue</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Intvalue</em>'.
   * @see br.unb.cic.obron.ide.oberon.Expression#getIntvalue()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_Intvalue();

  /**
   * Returns the meta object for the attribute '{@link br.unb.cic.obron.ide.oberon.Expression#getBoolvalue <em>Boolvalue</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Boolvalue</em>'.
   * @see br.unb.cic.obron.ide.oberon.Expression#getBoolvalue()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_Boolvalue();

  /**
   * Returns the meta object for the attribute '{@link br.unb.cic.obron.ide.oberon.Expression#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see br.unb.cic.obron.ide.oberon.Expression#getName()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_Name();

  /**
   * Returns the meta object for the containment reference list '{@link br.unb.cic.obron.ide.oberon.Expression#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Args</em>'.
   * @see br.unb.cic.obron.ide.oberon.Expression#getArgs()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Args();

  /**
   * Returns the meta object for the attribute list '{@link br.unb.cic.obron.ide.oberon.Expression#getAtribs <em>Atribs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Atribs</em>'.
   * @see br.unb.cic.obron.ide.oberon.Expression#getAtribs()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_Atribs();

  /**
   * Returns the meta object for the containment reference list '{@link br.unb.cic.obron.ide.oberon.Expression#getIndex <em>Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Index</em>'.
   * @see br.unb.cic.obron.ide.oberon.Expression#getIndex()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Index();

  /**
   * Returns the meta object for class '{@link br.unb.cic.obron.ide.oberon.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation</em>'.
   * @see br.unb.cic.obron.ide.oberon.Operation
   * @generated
   */
  EClass getOperation();

  /**
   * Returns the meta object for the attribute '{@link br.unb.cic.obron.ide.oberon.Operation#getOperationRelacional <em>Operation Relacional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operation Relacional</em>'.
   * @see br.unb.cic.obron.ide.oberon.Operation#getOperationRelacional()
   * @see #getOperation()
   * @generated
   */
  EAttribute getOperation_OperationRelacional();

  /**
   * Returns the meta object for the attribute '{@link br.unb.cic.obron.ide.oberon.Operation#getOperationAritmetic <em>Operation Aritmetic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operation Aritmetic</em>'.
   * @see br.unb.cic.obron.ide.oberon.Operation#getOperationAritmetic()
   * @see #getOperation()
   * @generated
   */
  EAttribute getOperation_OperationAritmetic();

  /**
   * Returns the meta object for the attribute '{@link br.unb.cic.obron.ide.oberon.Operation#getOperationLogic <em>Operation Logic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operation Logic</em>'.
   * @see br.unb.cic.obron.ide.oberon.Operation#getOperationLogic()
   * @see #getOperation()
   * @generated
   */
  EAttribute getOperation_OperationLogic();

  /**
   * Returns the meta object for class '{@link br.unb.cic.obron.ide.oberon.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see br.unb.cic.obron.ide.oberon.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.Statement#getStmt <em>Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Stmt</em>'.
   * @see br.unb.cic.obron.ide.oberon.Statement#getStmt()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Stmt();

  /**
   * Returns the meta object for the containment reference list '{@link br.unb.cic.obron.ide.oberon.Statement#getStmts <em>Stmts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Stmts</em>'.
   * @see br.unb.cic.obron.ide.oberon.Statement#getStmts()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Stmts();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.Statement#getDes <em>Des</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Des</em>'.
   * @see br.unb.cic.obron.ide.oberon.Statement#getDes()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Des();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.Statement#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see br.unb.cic.obron.ide.oberon.Statement#getExp()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Exp();

  /**
   * Returns the meta object for the attribute '{@link br.unb.cic.obron.ide.oberon.Statement#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var</em>'.
   * @see br.unb.cic.obron.ide.oberon.Statement#getVar()
   * @see #getStatement()
   * @generated
   */
  EAttribute getStatement_Var();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.Statement#getCond <em>Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cond</em>'.
   * @see br.unb.cic.obron.ide.oberon.Statement#getCond()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Cond();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.Statement#getThenStmt <em>Then Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Then Stmt</em>'.
   * @see br.unb.cic.obron.ide.oberon.Statement#getThenStmt()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_ThenStmt();

  /**
   * Returns the meta object for the containment reference list '{@link br.unb.cic.obron.ide.oberon.Statement#getElsifs <em>Elsifs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elsifs</em>'.
   * @see br.unb.cic.obron.ide.oberon.Statement#getElsifs()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Elsifs();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.Statement#getElseStmt <em>Else Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Else Stmt</em>'.
   * @see br.unb.cic.obron.ide.oberon.Statement#getElseStmt()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_ElseStmt();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.Statement#getInit <em>Init</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Init</em>'.
   * @see br.unb.cic.obron.ide.oberon.Statement#getInit()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Init();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.Statement#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see br.unb.cic.obron.ide.oberon.Statement#getCondition()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Condition();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.Statement#getMin <em>Min</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Min</em>'.
   * @see br.unb.cic.obron.ide.oberon.Statement#getMin()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Min();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.Statement#getMax <em>Max</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Max</em>'.
   * @see br.unb.cic.obron.ide.oberon.Statement#getMax()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Max();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.Statement#getCase <em>Case</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Case</em>'.
   * @see br.unb.cic.obron.ide.oberon.Statement#getCase()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Case();

  /**
   * Returns the meta object for the containment reference list '{@link br.unb.cic.obron.ide.oberon.Statement#getCases <em>Cases</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cases</em>'.
   * @see br.unb.cic.obron.ide.oberon.Statement#getCases()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Cases();

  /**
   * Returns the meta object for the attribute '{@link br.unb.cic.obron.ide.oberon.Statement#getExit <em>Exit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Exit</em>'.
   * @see br.unb.cic.obron.ide.oberon.Statement#getExit()
   * @see #getStatement()
   * @generated
   */
  EAttribute getStatement_Exit();

  /**
   * Returns the meta object for class '{@link br.unb.cic.obron.ide.oberon.Designator <em>Designator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Designator</em>'.
   * @see br.unb.cic.obron.ide.oberon.Designator
   * @generated
   */
  EClass getDesignator();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.Designator#getDesignator <em>Designator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Designator</em>'.
   * @see br.unb.cic.obron.ide.oberon.Designator#getDesignator()
   * @see #getDesignator()
   * @generated
   */
  EReference getDesignator_Designator();

  /**
   * Returns the meta object for the containment reference list '{@link br.unb.cic.obron.ide.oberon.Designator#getIndexes <em>Indexes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Indexes</em>'.
   * @see br.unb.cic.obron.ide.oberon.Designator#getIndexes()
   * @see #getDesignator()
   * @generated
   */
  EReference getDesignator_Indexes();

  /**
   * Returns the meta object for the attribute list '{@link br.unb.cic.obron.ide.oberon.Designator#getAtribs <em>Atribs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Atribs</em>'.
   * @see br.unb.cic.obron.ide.oberon.Designator#getAtribs()
   * @see #getDesignator()
   * @generated
   */
  EAttribute getDesignator_Atribs();

  /**
   * Returns the meta object for the attribute '{@link br.unb.cic.obron.ide.oberon.Designator#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see br.unb.cic.obron.ide.oberon.Designator#getName()
   * @see #getDesignator()
   * @generated
   */
  EAttribute getDesignator_Name();

  /**
   * Returns the meta object for the containment reference list '{@link br.unb.cic.obron.ide.oberon.Designator#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Args</em>'.
   * @see br.unb.cic.obron.ide.oberon.Designator#getArgs()
   * @see #getDesignator()
   * @generated
   */
  EReference getDesignator_Args();

  /**
   * Returns the meta object for class '{@link br.unb.cic.obron.ide.oberon.caseAlternative <em>case Alternative</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>case Alternative</em>'.
   * @see br.unb.cic.obron.ide.oberon.caseAlternative
   * @generated
   */
  EClass getcaseAlternative();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.caseAlternative#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see br.unb.cic.obron.ide.oberon.caseAlternative#getExp()
   * @see #getcaseAlternative()
   * @generated
   */
  EReference getcaseAlternative_Exp();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.caseAlternative#getMax <em>Max</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Max</em>'.
   * @see br.unb.cic.obron.ide.oberon.caseAlternative#getMax()
   * @see #getcaseAlternative()
   * @generated
   */
  EReference getcaseAlternative_Max();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.caseAlternative#getStmt <em>Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Stmt</em>'.
   * @see br.unb.cic.obron.ide.oberon.caseAlternative#getStmt()
   * @see #getcaseAlternative()
   * @generated
   */
  EReference getcaseAlternative_Stmt();

  /**
   * Returns the meta object for class '{@link br.unb.cic.obron.ide.oberon.elseIfStmt <em>else If Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>else If Stmt</em>'.
   * @see br.unb.cic.obron.ide.oberon.elseIfStmt
   * @generated
   */
  EClass getelseIfStmt();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.elseIfStmt#getCond <em>Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cond</em>'.
   * @see br.unb.cic.obron.ide.oberon.elseIfStmt#getCond()
   * @see #getelseIfStmt()
   * @generated
   */
  EReference getelseIfStmt_Cond();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.elseIfStmt#getStmt <em>Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Stmt</em>'.
   * @see br.unb.cic.obron.ide.oberon.elseIfStmt#getStmt()
   * @see #getelseIfStmt()
   * @generated
   */
  EReference getelseIfStmt_Stmt();

  /**
   * Returns the meta object for class '{@link br.unb.cic.obron.ide.oberon.OberonType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see br.unb.cic.obron.ide.oberon.OberonType
   * @generated
   */
  EClass getOberonType();

  /**
   * Returns the meta object for the attribute '{@link br.unb.cic.obron.ide.oberon.OberonType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see br.unb.cic.obron.ide.oberon.OberonType#getName()
   * @see #getOberonType()
   * @generated
   */
  EAttribute getOberonType_Name();

  /**
   * Returns the meta object for the attribute '{@link br.unb.cic.obron.ide.oberon.OberonType#getNumElement <em>Num Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Num Element</em>'.
   * @see br.unb.cic.obron.ide.oberon.OberonType#getNumElement()
   * @see #getOberonType()
   * @generated
   */
  EAttribute getOberonType_NumElement();

  /**
   * Returns the meta object for the containment reference '{@link br.unb.cic.obron.ide.oberon.OberonType#getNameType <em>Name Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Name Type</em>'.
   * @see br.unb.cic.obron.ide.oberon.OberonType#getNameType()
   * @see #getOberonType()
   * @generated
   */
  EReference getOberonType_NameType();

  /**
   * Returns the meta object for class '{@link br.unb.cic.obron.ide.oberon.Declararion <em>Declararion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declararion</em>'.
   * @see br.unb.cic.obron.ide.oberon.Declararion
   * @generated
   */
  EClass getDeclararion();

  /**
   * Returns the meta object for the containment reference list '{@link br.unb.cic.obron.ide.oberon.Declararion#getTypes <em>Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Types</em>'.
   * @see br.unb.cic.obron.ide.oberon.Declararion#getTypes()
   * @see #getDeclararion()
   * @generated
   */
  EReference getDeclararion_Types();

  /**
   * Returns the meta object for the containment reference list '{@link br.unb.cic.obron.ide.oberon.Declararion#getConsts <em>Consts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Consts</em>'.
   * @see br.unb.cic.obron.ide.oberon.Declararion#getConsts()
   * @see #getDeclararion()
   * @generated
   */
  EReference getDeclararion_Consts();

  /**
   * Returns the meta object for the containment reference list '{@link br.unb.cic.obron.ide.oberon.Declararion#getVars <em>Vars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Vars</em>'.
   * @see br.unb.cic.obron.ide.oberon.Declararion#getVars()
   * @see #getDeclararion()
   * @generated
   */
  EReference getDeclararion_Vars();

  /**
   * Returns the meta object for the containment reference list '{@link br.unb.cic.obron.ide.oberon.Declararion#getProc <em>Proc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Proc</em>'.
   * @see br.unb.cic.obron.ide.oberon.Declararion#getProc()
   * @see #getDeclararion()
   * @generated
   */
  EReference getDeclararion_Proc();

  /**
   * Returns the meta object for class '{@link br.unb.cic.obron.ide.oberon.Integer <em>Integer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Integer</em>'.
   * @see br.unb.cic.obron.ide.oberon.Integer
   * @generated
   */
  EClass getInteger();

  /**
   * Returns the meta object for class '{@link br.unb.cic.obron.ide.oberon.Boolean <em>Boolean</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean</em>'.
   * @see br.unb.cic.obron.ide.oberon.Boolean
   * @generated
   */
  EClass getBoolean();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  OberonFactory getOberonFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link br.unb.cic.obron.ide.oberon.impl.OberonImpl <em>Oberon</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.obron.ide.oberon.impl.OberonImpl
     * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getOberon()
     * @generated
     */
    EClass OBERON = eINSTANCE.getOberon();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBERON__NAME = eINSTANCE.getOberon_Name();

    /**
     * The meta object literal for the '<em><b>Declaration</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBERON__DECLARATION = eINSTANCE.getOberon_Declaration();

    /**
     * The meta object literal for the '<em><b>Block</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBERON__BLOCK = eINSTANCE.getOberon_Block();

    /**
     * The meta object literal for the '{@link br.unb.cic.obron.ide.oberon.impl.BlockImpl <em>Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.obron.ide.oberon.impl.BlockImpl
     * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getBlock()
     * @generated
     */
    EClass BLOCK = eINSTANCE.getBlock();

    /**
     * The meta object literal for the '<em><b>Stmt</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BLOCK__STMT = eINSTANCE.getBlock_Stmt();

    /**
     * The meta object literal for the '{@link br.unb.cic.obron.ide.oberon.impl.DeclarationsImpl <em>Declarations</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.obron.ide.oberon.impl.DeclarationsImpl
     * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getDeclarations()
     * @generated
     */
    EClass DECLARATIONS = eINSTANCE.getDeclarations();

    /**
     * The meta object literal for the '{@link br.unb.cic.obron.ide.oberon.impl.UserTypeDeclarationImpl <em>User Type Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.obron.ide.oberon.impl.UserTypeDeclarationImpl
     * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getUserTypeDeclaration()
     * @generated
     */
    EClass USER_TYPE_DECLARATION = eINSTANCE.getUserTypeDeclaration();

    /**
     * The meta object literal for the '<em><b>Name Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USER_TYPE_DECLARATION__NAME_TYPE = eINSTANCE.getUserTypeDeclaration_NameType();

    /**
     * The meta object literal for the '<em><b>Length</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USER_TYPE_DECLARATION__LENGTH = eINSTANCE.getUserTypeDeclaration_Length();

    /**
     * The meta object literal for the '<em><b>Vartype</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USER_TYPE_DECLARATION__VARTYPE = eINSTANCE.getUserTypeDeclaration_Vartype();

    /**
     * The meta object literal for the '<em><b>Vars</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USER_TYPE_DECLARATION__VARS = eINSTANCE.getUserTypeDeclaration_Vars();

    /**
     * The meta object literal for the '{@link br.unb.cic.obron.ide.oberon.impl.ConstantImpl <em>Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.obron.ide.oberon.impl.ConstantImpl
     * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getConstant()
     * @generated
     */
    EClass CONSTANT = eINSTANCE.getConstant();

    /**
     * The meta object literal for the '<em><b>Const Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTANT__CONST_NAME = eINSTANCE.getConstant_ConstName();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONSTANT__EXP = eINSTANCE.getConstant_Exp();

    /**
     * The meta object literal for the '{@link br.unb.cic.obron.ide.oberon.impl.VarDeclarationImpl <em>Var Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.obron.ide.oberon.impl.VarDeclarationImpl
     * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getVarDeclaration()
     * @generated
     */
    EClass VAR_DECLARATION = eINSTANCE.getVarDeclaration();

    /**
     * The meta object literal for the '<em><b>Vars</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VAR_DECLARATION__VARS = eINSTANCE.getVarDeclaration_Vars();

    /**
     * The meta object literal for the '<em><b>Var Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VAR_DECLARATION__VAR_TYPE = eINSTANCE.getVarDeclaration_VarType();

    /**
     * The meta object literal for the '{@link br.unb.cic.obron.ide.oberon.impl.ProcedureImpl <em>Procedure</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.obron.ide.oberon.impl.ProcedureImpl
     * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getProcedure()
     * @generated
     */
    EClass PROCEDURE = eINSTANCE.getProcedure();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROCEDURE__NAME = eINSTANCE.getProcedure_Name();

    /**
     * The meta object literal for the '<em><b>Formals</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCEDURE__FORMALS = eINSTANCE.getProcedure_Formals();

    /**
     * The meta object literal for the '<em><b>Procedure Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCEDURE__PROCEDURE_TYPE = eINSTANCE.getProcedure_ProcedureType();

    /**
     * The meta object literal for the '<em><b>Decl</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCEDURE__DECL = eINSTANCE.getProcedure_Decl();

    /**
     * The meta object literal for the '<em><b>Block</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROCEDURE__BLOCK = eINSTANCE.getProcedure_Block();

    /**
     * The meta object literal for the '{@link br.unb.cic.obron.ide.oberon.impl.FormalsImpl <em>Formals</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.obron.ide.oberon.impl.FormalsImpl
     * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getFormals()
     * @generated
     */
    EClass FORMALS = eINSTANCE.getFormals();

    /**
     * The meta object literal for the '<em><b>Arg</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORMALS__ARG = eINSTANCE.getFormals_Arg();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORMALS__ARGS = eINSTANCE.getFormals_Args();

    /**
     * The meta object literal for the '{@link br.unb.cic.obron.ide.oberon.impl.FormalArgImpl <em>Formal Arg</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.obron.ide.oberon.impl.FormalArgImpl
     * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getFormalArg()
     * @generated
     */
    EClass FORMAL_ARG = eINSTANCE.getFormalArg();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FORMAL_ARG__ARGS = eINSTANCE.getFormalArg_Args();

    /**
     * The meta object literal for the '<em><b>Arg Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORMAL_ARG__ARG_TYPE = eINSTANCE.getFormalArg_ArgType();

    /**
     * The meta object literal for the '{@link br.unb.cic.obron.ide.oberon.impl.ArgumentsImpl <em>Arguments</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.obron.ide.oberon.impl.ArgumentsImpl
     * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getArguments()
     * @generated
     */
    EClass ARGUMENTS = eINSTANCE.getArguments();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARGUMENTS__EXP = eINSTANCE.getArguments_Exp();

    /**
     * The meta object literal for the '<em><b>Exps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARGUMENTS__EXPS = eINSTANCE.getArguments_Exps();

    /**
     * The meta object literal for the '{@link br.unb.cic.obron.ide.oberon.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.obron.ide.oberon.impl.ExpressionImpl
     * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__LEFT = eINSTANCE.getExpression_Left();

    /**
     * The meta object literal for the '<em><b>Opr</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__OPR = eINSTANCE.getExpression_Opr();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__RIGHT = eINSTANCE.getExpression_Right();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__EXP = eINSTANCE.getExpression_Exp();

    /**
     * The meta object literal for the '<em><b>Intvalue</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__INTVALUE = eINSTANCE.getExpression_Intvalue();

    /**
     * The meta object literal for the '<em><b>Boolvalue</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__BOOLVALUE = eINSTANCE.getExpression_Boolvalue();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__NAME = eINSTANCE.getExpression_Name();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__ARGS = eINSTANCE.getExpression_Args();

    /**
     * The meta object literal for the '<em><b>Atribs</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__ATRIBS = eINSTANCE.getExpression_Atribs();

    /**
     * The meta object literal for the '<em><b>Index</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__INDEX = eINSTANCE.getExpression_Index();

    /**
     * The meta object literal for the '{@link br.unb.cic.obron.ide.oberon.impl.OperationImpl <em>Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.obron.ide.oberon.impl.OperationImpl
     * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getOperation()
     * @generated
     */
    EClass OPERATION = eINSTANCE.getOperation();

    /**
     * The meta object literal for the '<em><b>Operation Relacional</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATION__OPERATION_RELACIONAL = eINSTANCE.getOperation_OperationRelacional();

    /**
     * The meta object literal for the '<em><b>Operation Aritmetic</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATION__OPERATION_ARITMETIC = eINSTANCE.getOperation_OperationAritmetic();

    /**
     * The meta object literal for the '<em><b>Operation Logic</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPERATION__OPERATION_LOGIC = eINSTANCE.getOperation_OperationLogic();

    /**
     * The meta object literal for the '{@link br.unb.cic.obron.ide.oberon.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.obron.ide.oberon.impl.StatementImpl
     * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '<em><b>Stmt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__STMT = eINSTANCE.getStatement_Stmt();

    /**
     * The meta object literal for the '<em><b>Stmts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__STMTS = eINSTANCE.getStatement_Stmts();

    /**
     * The meta object literal for the '<em><b>Des</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__DES = eINSTANCE.getStatement_Des();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__EXP = eINSTANCE.getStatement_Exp();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMENT__VAR = eINSTANCE.getStatement_Var();

    /**
     * The meta object literal for the '<em><b>Cond</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__COND = eINSTANCE.getStatement_Cond();

    /**
     * The meta object literal for the '<em><b>Then Stmt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__THEN_STMT = eINSTANCE.getStatement_ThenStmt();

    /**
     * The meta object literal for the '<em><b>Elsifs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__ELSIFS = eINSTANCE.getStatement_Elsifs();

    /**
     * The meta object literal for the '<em><b>Else Stmt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__ELSE_STMT = eINSTANCE.getStatement_ElseStmt();

    /**
     * The meta object literal for the '<em><b>Init</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__INIT = eINSTANCE.getStatement_Init();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__CONDITION = eINSTANCE.getStatement_Condition();

    /**
     * The meta object literal for the '<em><b>Min</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__MIN = eINSTANCE.getStatement_Min();

    /**
     * The meta object literal for the '<em><b>Max</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__MAX = eINSTANCE.getStatement_Max();

    /**
     * The meta object literal for the '<em><b>Case</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__CASE = eINSTANCE.getStatement_Case();

    /**
     * The meta object literal for the '<em><b>Cases</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__CASES = eINSTANCE.getStatement_Cases();

    /**
     * The meta object literal for the '<em><b>Exit</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATEMENT__EXIT = eINSTANCE.getStatement_Exit();

    /**
     * The meta object literal for the '{@link br.unb.cic.obron.ide.oberon.impl.DesignatorImpl <em>Designator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.obron.ide.oberon.impl.DesignatorImpl
     * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getDesignator()
     * @generated
     */
    EClass DESIGNATOR = eINSTANCE.getDesignator();

    /**
     * The meta object literal for the '<em><b>Designator</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DESIGNATOR__DESIGNATOR = eINSTANCE.getDesignator_Designator();

    /**
     * The meta object literal for the '<em><b>Indexes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DESIGNATOR__INDEXES = eINSTANCE.getDesignator_Indexes();

    /**
     * The meta object literal for the '<em><b>Atribs</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DESIGNATOR__ATRIBS = eINSTANCE.getDesignator_Atribs();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DESIGNATOR__NAME = eINSTANCE.getDesignator_Name();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DESIGNATOR__ARGS = eINSTANCE.getDesignator_Args();

    /**
     * The meta object literal for the '{@link br.unb.cic.obron.ide.oberon.impl.caseAlternativeImpl <em>case Alternative</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.obron.ide.oberon.impl.caseAlternativeImpl
     * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getcaseAlternative()
     * @generated
     */
    EClass CASE_ALTERNATIVE = eINSTANCE.getcaseAlternative();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CASE_ALTERNATIVE__EXP = eINSTANCE.getcaseAlternative_Exp();

    /**
     * The meta object literal for the '<em><b>Max</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CASE_ALTERNATIVE__MAX = eINSTANCE.getcaseAlternative_Max();

    /**
     * The meta object literal for the '<em><b>Stmt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CASE_ALTERNATIVE__STMT = eINSTANCE.getcaseAlternative_Stmt();

    /**
     * The meta object literal for the '{@link br.unb.cic.obron.ide.oberon.impl.elseIfStmtImpl <em>else If Stmt</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.obron.ide.oberon.impl.elseIfStmtImpl
     * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getelseIfStmt()
     * @generated
     */
    EClass ELSE_IF_STMT = eINSTANCE.getelseIfStmt();

    /**
     * The meta object literal for the '<em><b>Cond</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELSE_IF_STMT__COND = eINSTANCE.getelseIfStmt_Cond();

    /**
     * The meta object literal for the '<em><b>Stmt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELSE_IF_STMT__STMT = eINSTANCE.getelseIfStmt_Stmt();

    /**
     * The meta object literal for the '{@link br.unb.cic.obron.ide.oberon.impl.OberonTypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.obron.ide.oberon.impl.OberonTypeImpl
     * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getOberonType()
     * @generated
     */
    EClass OBERON_TYPE = eINSTANCE.getOberonType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBERON_TYPE__NAME = eINSTANCE.getOberonType_Name();

    /**
     * The meta object literal for the '<em><b>Num Element</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBERON_TYPE__NUM_ELEMENT = eINSTANCE.getOberonType_NumElement();

    /**
     * The meta object literal for the '<em><b>Name Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBERON_TYPE__NAME_TYPE = eINSTANCE.getOberonType_NameType();

    /**
     * The meta object literal for the '{@link br.unb.cic.obron.ide.oberon.impl.DeclararionImpl <em>Declararion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.obron.ide.oberon.impl.DeclararionImpl
     * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getDeclararion()
     * @generated
     */
    EClass DECLARARION = eINSTANCE.getDeclararion();

    /**
     * The meta object literal for the '<em><b>Types</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECLARARION__TYPES = eINSTANCE.getDeclararion_Types();

    /**
     * The meta object literal for the '<em><b>Consts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECLARARION__CONSTS = eINSTANCE.getDeclararion_Consts();

    /**
     * The meta object literal for the '<em><b>Vars</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECLARARION__VARS = eINSTANCE.getDeclararion_Vars();

    /**
     * The meta object literal for the '<em><b>Proc</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECLARARION__PROC = eINSTANCE.getDeclararion_Proc();

    /**
     * The meta object literal for the '{@link br.unb.cic.obron.ide.oberon.impl.IntegerImpl <em>Integer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.obron.ide.oberon.impl.IntegerImpl
     * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getInteger()
     * @generated
     */
    EClass INTEGER = eINSTANCE.getInteger();

    /**
     * The meta object literal for the '{@link br.unb.cic.obron.ide.oberon.impl.BooleanImpl <em>Boolean</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see br.unb.cic.obron.ide.oberon.impl.BooleanImpl
     * @see br.unb.cic.obron.ide.oberon.impl.OberonPackageImpl#getBoolean()
     * @generated
     */
    EClass BOOLEAN = eINSTANCE.getBoolean();

  }

} //OberonPackage
