/*
 * generated by Xtext 2.25.0
 */
package br.unb.cic.obron.ide.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link OberonWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractOberonWebModule extends DefaultWebModule {

}
