/*
 * generated by Xtext 2.25.0
 */
package br.unb.cic.obron.ide.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractOberonValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(br.unb.cic.obron.ide.oberon.OberonPackage.eINSTANCE);
		return result;
	}
}
