/*
 * generated by Xtext 2.25.0
 */
package br.unb.cic.obron.ide.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class OberonAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("br/unb/cic/obron/ide/parser/antlr/internal/InternalOberon.tokens");
	}
}
