/*
 * generated by Xtext 2.25.0
 */
package br.unb.cic.obron.ide.ui;

import br.unb.cic.obron.ide.ui.internal.IdeActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class OberonExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(IdeActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		IdeActivator activator = IdeActivator.getInstance();
		return activator != null ? activator.getInjector(IdeActivator.BR_UNB_CIC_OBRON_IDE_OBERON) : null;
	}

}
